routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/posts', 'PostController');
Route::resource('/postcategorys', 'PostCategoryController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title','description','image','user_id','post_category_id'];

    public function user()
   {
   	return $this->belongsTo('App\User');
   }

   public function post_category()
   {
   	return $this->belongsTo('App\PostCategory');
   }
}

app/PostCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PostCategory extends Model
{
    protected $fillable = ['name','slug','description'];

    public function post()
    {
    	return $this->hasMany('App\Post');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\PostCategory;

class PostCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $postcategorys = PostCategory::all();
        return view('posts.postcategory', compact('postcategorys'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        PostCategory::create($input);
        return redirect('postcategorys');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $postcategorys = PostCategory::all();
        $posts = PostCategory::findOrFail($id)->post()->get();
        return view('posts.postcategory',compact('posts','postcategorys'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Post;
use App\PostCategory;
use Illuminate\Support\Facades\Session;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts= Post::all();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $postcategorys = PostCategory::all();
        return view('posts.create', compact('postcategorys'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request, [
            'title' => 'required|unique:posts',
            'description'=> 'required',
            'image' => 'required'
        ]);
        $input = $request->all();
        //dd($input);
        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }else{
            $input['image'] = 'img/default.jpg';
        }
        $input['user_id'] = Auth::user()->id;
        Post::create($input);
        Session::flash('status', 'Post Created Successfully');
        return redirect('posts');
    }
    public function upload($file)
    {
        $extension = $file->getClientOriginalExtension();
        $sha = sha1($file->getClientOriginalName());
        $filename = date('Y-m-d-h-i-s')."-".$sha.".".$extension;
        $path = public_path('img/posts/');
        $file->move($path, $filename);
        return 'img/posts/'.$filename;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $postcategorys = PostCategory::all();
        return view('posts.edit')->with('post',$post)->with('postcategorys',$postcategorys);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|unique:posts',
            'description'=> 'required',
        ]);
        $post = Post::findOrFail($id);
        $input = $request->all();
        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }
        $input['user_id'] = Auth::user()->id;
        $post->update($input);
        Session::flash('status', 'Post Updated Successfully');
        return redirect('posts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findOrFail($id)->delete();
        Session::flash('status1', 'Post Deleted Successfully');
        return redirect()->back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
</head>
<body style="background: #3a8259;">
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a style="color: green;" href="{{url('/posts')}}"><strong>Posts</strong></a></li>
                        <li><a style="color: green;" href="{{url('/postcategorys')}}"><strong>Post Category</strong></a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>
    
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    @yield('scripts')
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12" style="background: #fff;">
			<div class="panel-heading">
				<h1 style="margin-left:155px; ">Create Post<a href="{{route('posts.index')}}" class="btn btn-success pull-right">Back</a></h1>
			</div>
			<div class="col-sm-8 col-sm-offset-2">
				@if(count($errors->all())>0)
				<div class="alert alert-danger">
					<ul>	
						@foreach($errors->all() as $error)
							<li>{{$error}}</li>
						@endforeach
					</ul>
				</div>
				@endif
				<div class="panel panel-primary">
					<div class="panel-heading">Create Posts</div>
					<div class="panel-body">
						<form action="{{route('posts.store')}}" method="POST" enctype="Multipart/form-data">
							{{csrf_field('PUT')}}
							<div class="form-group">
								<label for="title">Title</label>
								<input type="text" name="title" id="title" class="form-control">
							</div>
							<div class="form-group">
								<label for="image">Image</label>
								<input type="file" name="image" id="image" class="form-control">
							</div>
						<div class="form-group">
						<label for="post_category_id">Select a Category</label>
						<select name="post_category_id" id="post_category_id">
							@foreach($postcategorys as $postcategory)
							<option value="{{$postcategory->id}}">{{$postcategory->name}}</option>
							@endforeach
						</select>
					</div>
							<div class="form-group">
								<label for="description">Description</label>
								<textarea name="description" id="description" cols="20" rows="5" class="form-control"></textarea>
							</div>
							<button class="btn btn-primary">Create</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12" style="background: #fff;">
			<div class="panel-heading">
				<h1 style="margin-left:155px; ">Update Post<a href="{{route('posts.index')}}" class="btn btn-success pull-right">Back</a></h1>
			</div>
			@if(session('status'))
			<div class="alert alert-success">
				{{session('status')}}
			</div>
			@endif
			<div class="col-sm-8 col-sm-offset-2">
				@if(count($errors->all())>0)
				<div class="alert alert-danger">
					<ul>	
						@foreach($errors->all() as $error)
							<li>{{$error}}</li>
						@endforeach
					</ul>
				</div>
				@endif
				<div class="panel panel-primary">
					<div class="panel-heading">Update Posts</div>
					<div class="panel-body">
						<form action="{{route('posts.update',$post->id)}}" method="POST" enctype="Multipart/form-data">
							{{method_field('PUT')}}
							{{csrf_field()}}
									<div class="form-group">
										<label for="title">Title</label>
										<input type="text" name="title" id="title" value="{{$post->title}}" class="form-control">
									</div>
									<div class="row">
										<div class="col-sm-6">
											<div class="form-group">
												<label for="image">Image</label>
												<input type="file" name="image" id="image" class="form-control">
											</div>

										<div class="col-sm-6">
											<div class="form-group">
											<label for="post_category_id">Select a Category</label>
											<select name="post_category_id" id="post_category_id">
												@foreach($postcategorys as $postcategory)
												<option value="{{$postcategory->id}}" @if($postcategory->id == $post->post_category_id) Selected @endif>{{$postcategory->name}}</option>
												@endforeach
											</select>
											</div>
										</div>
										
										<div class="col-sm-6">
											<img class="img-thumbnail" src="{{asset($post->image)}}" width="80" height="80">
										</div>
										</div>
									</div>
										<div class="form-group">
											<label for="description">Description</label>
											<textarea name="description" id="description" cols="20" rows="5" class="form-control">{{$post->description}}</textarea>
										</div>

							<button class="btn btn-primary">Update</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12" style="background: #fff;">
			<div class="panel-heading">
				<h1>All Posts<a href="{{route('posts.create')}}" class="btn btn-primary pull-right">Create Post</a></h1>
			</div>
			@if(session('status'))
			<div class="alert alert-success">
				{{session('status')}}
			</div>
			@endif
			@if(session('status1'))
			<div class="alert alert-danger">
				{{session('status1')}}
			</div>
			@endif
			
			<div class="col-sm-12 col-sm-offset-0">
				<div class="panel panel-primary">
					<div class="panel-heading">Post List</div>
					<div class="panel-body">
						<table id="myTable" class="table table-bordered table-striped">
						<thead>
							<tr>
								<td>Sl</td>
								<td>Title</td>
								<td>Description</td>
								<td>Image</td>
								<td>Created by</td>
								<td>Category</td>
								<td>Date</td>
								<td width="180">Action</td>
							</tr>
						</thead>
						<tbody>
							@foreach($posts as $post)
							<tr>
								<td>{{$post->id}}</td>
								<td>{{$post->title}}</td>
								<td>{{$post->description}}</td>
								<td><img src="{{$post->image}}" class="img-thumbnail" width="100" height="100"></td>
								<td>{{$post->user->name}}</td>
								<td>{{$post->post_category->name}}</td>
								<td>{{$post->user->created_at->toFormattedDateString()}}</td>
								<td>
									<a class="btn btn-primary btn-lg" href="{{route('posts.show',$post->id)}}"><i class="glyphicon glyphicon-eye-open"></i></a>
									<a class="btn btn-warning btn-lg" href="{{route('posts.edit',$post->id)}}"><i class="glyphicon glyphicon-edit"></i></a>
									<a href="#" onclick="return confirm('Are You Sure')" >
										<form style="display: inline-block;" action="{{route('posts.destroy',$post->id)}}" method="POST">
											{{csrf_field()}}
											{{method_field('DELETE')}}
											<button class="btn btn-danger btn-lg"><i class="glyphicon glyphicon-trash" value="Delete"></i></button>
										</form>
									</a>
								</td>
							</tr>
							@endforeach
						</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
    $(document).ready(function(){
    $('#myTable').DataTable();
});
</script>
@endsection

resources/views/posts/postcategory.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-12" style="background: #fff;">
			<div class="panel-heading">
				<h1>All Categories <a href="#" class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal">Add a category</a></h1>
			</div>
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				<div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h4 class="modal-title" id="myModalLabel">Create Category</h4>
				      </div>
						    <div class="modal-body">
						        <form action="{{route('postcategorys.store')}}" method="POST">
						        	{{csrf_field()}}
						        	<div class="form-group">
						        		<label for="name">Post Category Name</label>
						        		<input type="text" name="name"  id="name" class="form-control">
						        	</div>
						        	<div class="form-group">
						        		<label for="slug">Post Category Slug</label>
						        		<input type="text" name="slug"  id="slug" class="form-control">
						        	</div>
						        	<div class="form-group">
						        		<label for="description">Post Category Description</label>
						        		<textarea name="description" id="description" cols="30" rows="5" class="form-control"></textarea>
						        	</div>
						        	<button type="submit" class="btn btn-primary">Add</button>
						        </form>
							</div>
					      	<div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					      	</div> 
				    </div>
				  </div>
				</div>
				<div class="col-sm-12 col-sm-offset-0">
				<div class="post-categories">
					<div style="margin-bottom: 10px;" class="btn-group" rol="group" aria-label="...">
						@foreach($postcategorys as $postcategory)
						<a href="{{route('postcategorys.show', $postcategory->id)}}"><button type="button" class="btn btn-success">{{$postcategory->name}}</button></a>
						@endforeach
					</div>
				</div>
				</div>
				<div class="col-sm-12 col-sm-offset-0">
					<div class="panel panel-primary">
						<div class="panel-heading">Post Detials</div>
							<div class="panel-body">
						<table id="myTable" class="table table-bordered table-striped">
							<thead>
								<tr>
									<td>Sl</td>
									<td>Title</td>
									<td>Description</td>
									<td>Image</td>
									<td>Created By</td>
									<td>Date</td>
								</tr>
							</thead>
							<tbody>
								@if(isset($posts))
								@foreach($posts as $post)
									<tr>
										<td>{{$post->id}}</td>
										<td>{{$post->title}}</td>
										<td>{{$post->description}}</td>
										<td><img src="{{asset($post->image)}}" alt="" class="img-responsive" width="100" height="100"></td>
										<td>{{$post->user->name}}</td>
										<td>{{$post->created_at->toFormattedDateString()}}</td>
									</tr>
								@endforeach
								
								@endif
							</tbody>
						</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
    $(document).ready(function(){
    $('#myTable').DataTable();
});
</script>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-12" style="background: #fff;">
			<div class="panel-heading">
				<h1>View Post<a href="{{route('posts.index')}}" class="btn btn-success pull-right">Back</a></h1>
			</div>
			<div class="col-sm-12 col-sm-offset-0">
				<div class="panel panel-primary">
					<div class="panel-heading">Post Detials</div>
					<div class="panel-body">
				<h3>Post Title : {{$post->title}}</h3>
				<p>Description: {{$post->description}}</p>
				<p>Category: {{$post->post_category->name}}</p>
				<p>Image: <img src="{{asset($post->image)}}" width="80" height="80"></p>
				
			</div>
		</div>
	</div>
			</div>
		</div>
	</div>
@endsection